server:
  port: 9000

spring:
  h2:
    console:
      enabled: true
      path: /data
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true

  datasource:
    url: jdbc:h2:mem:Oauth
    username: sa
    password:
    driver-class-name: org.h2.Driver
